on:
  push:
    branches:
      - main  # Trigger on main branch push (e.g., after merging a PR)

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Provide the token for authentication

      # Step 2: Set up Git with user info
      - name: Set up Git
        run: |
          git config user.name "vishnu4reddy"
          git config user.email "vishnu4reddy@users.noreply.github.com"

      # Step 3: Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh

      # Step 4: Get list of open PRs and filter duplicates
      - name: Get list of open PRs
        id: pr_list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set the token explicitly for the `gh` CLI
        run: |
          prs=$(gh pr list --state open --json number,headRefName --jq '.[] | "\(.number) \(.headRefName)"')

          # Filter duplicates using jq
          unique_prs=$(echo "$prs" | sort | uniq)

          # Save the unique PRs to the environment file
          echo "prs=$unique_prs" >> $GITHUB_ENV
          
          echo "Filtered unique PRs: $unique_prs"

      # Step 5: Rebase the open PRs using the latest commit from the main branch
      - name: Rebase remaining PRs onto main branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure authentication for git commands as well
        run: |
          # Get the latest commit hash from the main branch
          latest_commit=$(git rev-parse origin/main)
          echo "Latest commit hash from main: $latest_commit"

          # Loop through each unique open PR and rebase onto the latest commit of the main branch
          for pr in $(echo "$prs" | sort | uniq); do
            # Extract PR number and branch name from the string
            pr_number=$(echo "$pr" | cut -d' ' -f1)
            pr_branch=$(echo "$pr" | cut -d' ' -f2)

            # Skip if the branch name is empty
            if [ -z "$pr_branch" ]; then
              echo "::error::Skipping PR #$pr_number because branch name is empty."
              continue
            fi

            echo "Rebasing PR #$pr_number ($pr_branch) onto main branch..."

            # Fetch the latest main branch and the PR branch
            git fetch origin

            # Checkout the main branch and pull the latest changes
            git checkout main
            git pull origin main

            # Checkout the PR branch and pull the latest changes from the PR branch
            git checkout "$pr_branch"
            git pull origin "$pr_branch"

            # Ensure there are no uncommitted changes before rebasing
            if [ -n "$(git status --porcelain)" ]; then
              echo "::error::There are uncommitted changes in PR #$pr_number ($pr_branch). Please commit or stash them before proceeding."
              continue
            fi

            # Start the rebase process
            echo "Starting rebase of PR #$pr_number onto latest commit from main..."

            # Rebase the PR branch onto the latest commit from the main branch
            git rebase $latest_commit || {
              echo "::error::Rebase failed for PR #$pr_number. Trying to skip conflicting commits."

              # Keep skipping the conflicting commits until the rebase is successful
              while ! git rebase --skip; do
                echo "::warning::Skipping commit due to conflict. Trying again..."
              done
            }

            # After the rebase is successful, push the rebased PR
            echo "Rebasing of PR #$pr_number ($pr_branch) successful!"

            # Set the remote URL with GitHub token for authentication during push
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/a/work1.git

            # Push the rebased branch back to GitHub
            git push origin "$pr_branch" --force-with-lease
            echo "Successfully pushed rebased PR #$pr_number ($pr_branch)."
          done
