name: Rebase Remaining PRs on Merge

on:
  push:
    branches:
      - main  # Trigger on main branch push (e.g., after merging a PR)

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the provided GitHub token to authenticate

      - name: Rebase remaining PRs onto main branch
        run: |
          # Fetch the latest main and PR branch
          git fetch origin main
          git fetch origin "$pr_branch"

          # Checkout the PR branch
          git checkout "$pr_branch"
          
          # Rebase the PR branch onto the latest main branch
          if git rebase origin/main; then
            echo "Rebasing of PR $pr_number successful!"
            
            # Push the rebased PR branch
            git push origin "$pr_branch" --force-with-lease
          else
            echo "Rebase failed for PR $pr_number."
            git rebase --abort
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Set the token explicitly in the environment
